spring.application.name=emergencyResponse

# Database Connection
# Notice the 5433 instead of 5432!
spring.datasource.url=jdbc:postgresql://localhost:5433/saferoute
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings (Optional but helpful for development)
# 'update' automatically creates and updates your database tables based on your Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000