spring.application.name=emergencyResponse

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/saferoute
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings (Optional but helpful for development)
# 'update' automatically creates and updates your database tables based on your Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect